events {
	worker_connections 100;
}

http {
	# proxy_read_timeout 300;
	# proxy_connect_timeout 300;
	# proxy_send_timeout 300;
	include /etc/nginx/mime.types;
	upstream fastapi_app {
		server chess_api:12345 fail_timeout=0;
	}

	server {
		server_name chess.com;
		listen 80;
		listen [::]:80;
		location / {
			return 301 https://$host$request_uri;
		}
		location ~ /.well-known/acme-challenge/ {
			root /var/www/certbot;
		}
	}

	server {
		listen 443 ssl;
		listen [::]:443 ssl;
		client_max_body_size 1G;
		keepalive_timeout 5;
		http2 on;
		server_name chess.com;

		ssl_certificate /etc/letsencrypt/live/chess.com/fullchain.pem;
		ssl_certificate_key /etc/letsencrypt/live/chess.com/privkey.pem;

		access_log /var/log/nginx/access.log;
		error_log /var/log/nginx/error.log;

		error_page 500 502 503 504 /50x.html;
		location = /50x.html {
			root /usr/share/nginx/html;
		}

		location /{
			proxy_pass http://fastapi_app/api/v1/docs;
		}

		location /api/v1 {
			#
			# CORS config for nginx
			#
			set $cors '';
			if ($http_origin = 'https://localhost:12345') {
				set $cors 'true';
			}

			if ($cors = 'true') {
				# Tell client that this pre-flight info is valid for 20 days
				add_header 'Access-Control-Allow-Origin' "$http_origin" always;
				add_header 'Access-Control-Allow-Credentials' 'true' always;
				add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS' always;
				add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;
				add_header 'Access-Control-Max-Age' 1728000;
				add_header 'Content-Type' 'text/plain charset=UTF-8';
				add_header 'Content-Length' 0;
			}
			proxy_pass http://fastapi_app/api/v1;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
		}

		location ~ ^/api/v1/(play|search|watch|room/ws) {
			proxy_pass http://fastapi_app$request_uri;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;

			# WebSocket support
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_read_timeout 86400;
			proxy_buffering off;
			proxy_cache off;

			# Security headers
			add_header X-Content-Type-Options nosniff;
			add_header X-XSS-Protection "1; mode=block";

			# Allow WebSocket protocol
			proxy_ssl_protocols TLSv1.2 TLSv1.3;
		}

	}
}
