"""Add Search, Move, Game tables

Revision ID: a6235295eabd
Revises: abb77959f847
Create Date: 2024-10-15 15:12:54.923955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a6235295eabd"
down_revision: Union[str, None] = "abb77959f847"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("winner_user_id", sa.BIGINT(), nullable=True),
        sa.Column("current_turn_user_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "fen",
            sa.String(length=100),
            server_default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
            nullable=False,
        ),
        sa.Column("white_piece_user_id", sa.BIGINT(), nullable=False),
        sa.Column("black_piece_user_id", sa.BIGINT(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["black_piece_user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_turn_user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.room_id"],
        ),
        sa.ForeignKeyConstraint(
            ["white_piece_user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("game_id"),
    )
    op.create_table(
        "search",
        sa.Column("search_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("rank", sa.BIGINT(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=True),
        sa.Column(
            "search_type", sa.Enum("SEEK", "WAIT", name="searchtype"), nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.room_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("search_id"),
    )
    op.create_table(
        "moves",
        sa.Column("move_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("move", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.game_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("move_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("moves")
    op.drop_table("search")
    op.drop_table("games")
    # ### end Alembic commands ###
