"""Add in_game column

Revision ID: a88b25fc605f
Revises: a6235295eabd
Create Date: 2024-11-10 16:39:41.669863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88b25fc605f'
down_revision: Union[str, None] = 'a6235295eabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_members', sa.Column('in_game', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_members', 'in_game')
    # ### end Alembic commands ###
